### ISSUE TITLE
Check C++ Streams

### ISSUE THREAD

**Issue by loverdos** [biboudis/clashofthelambdas#4]
https://jscheiny.github.io/Streams/

Are they inspired by Java Streams?

**Comment by palladin** [comment]
Yes it shares many common ideas with Java 8 Streams. 
I'm planning to investigate the core ideas of java 8 Streams in F#
https://github.com/nessos/Streams
because from our investigation we found that LINQ IEnumerable methods and F#'s Seq functions are not in par with the performance of Java 8 Streams.

**Comment by loverdos** [comment]
As a side note, I really think you should first decouple streams from lambdas as an approach in your research/measurements. Or at least study them both separate and combined. From the paper, the motivation why study them together is not clear, to me at least. Of course, it is legitimate.

**Comment by palladin** [comment]
We study them together because Lambdas + Stream APIs offer a path for mainstream adoption of FP-style, but the killer app of  the combination (Lambdas + Stream APIs)  is to offer an easy path to parallelism. I'm quoting from the abstract 
"The introduction of lambdas in Java 8 completes the slate of
statically-typed, mainstream languages with both object-oriented
and functional features. The main motivation for lambdas in Java
has been to facilitate stream-based declarative APIs, and, therefore,
easier parallelism"
